name: Deploy

on:
  push:
    tags:
      - '*.*.*'

jobs:     
  deploy:
    strategy:
      matrix:
        runs-on: [windows-latest, ubuntu-latest, macos-latest]
        python-version: [3.8, 3.9, '3.10', '3.11']
    runs-on: ${{ matrix.runs-on }}

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install --upgrade setuptools wheel twine
        python3 -m pip install -r ci_requirements.txt
    - name: Build wheels
      run: |
        python3 setup.py sdist
        python3 setup.py bdist_wheel
    - name: Publish source and wheels
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        python3 -m twine upload dist/*.whl
        python3 -m twine upload dist/*.tar.gz
